<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>13.0</LangVersion>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>true</GenerateProgramFile>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="507484246.tif" />
    <None Remove="assets\ti31149327_9330.tif" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Amaigoma\Amaigoma.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="assets\PineTools\image.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\text-extraction-for-ocr\507484246.tif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\text-extraction-for-ocr\ti31149327_9330.tif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\mirflickr08\*.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
